<!--<html>-->
<!---->
<!--<head>-->
<!--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
<!---->
<!--    <script type="text/javascript">-->
<!--        var obj = {-->
<!--            "module":"news",-->
<!--            "category":"politics",-->
<!--            "source":"liga",-->
<!--            "count":"20",-->
<!--            "older":"true",-->
<!--            "lastId":"-1"};-->
<!---->
<!--        function sendTestJSON() {-->
<!--            $.ajax({-->
<!--                "url": "/index/test",-->
<!--                "dataType": "json",-->
<!--                "type": "POST",-->
<!--                "data": JSON.stringify(obj),-->
<!--                "contentType": "application/json;charset=utf-8",-->
<!--                "success": function(data) {-->
<!--                    console.log(data);-->
<!--                }-->
<!--            });-->
<!--        }-->
<!--    </script>-->
<!--</head>-->
<!---->
<!--<body>-->
<!--    <button type="button" onclick="sendTestJSON();">Test</button>-->
<!--</body>-->
<!---->
<!--</html>-->

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Module</title>

    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->
    <!-- Latest compiled and minified CSS -->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">-->
    <!-- Optional theme -->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">-->
    <!-- Latest compiled and minified JavaScript -->
    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>-->

    <!--jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="../../../public/js/jquery-1.11.3.js"></script>
    <!--Include all compiled plugins (below), or include individual files as needed -->
    <script src="../../../public/js/bootstrap.js"></script>
    <!--Bootstrap -->
    <link href="../../../public/css/bootstrap.css" rel="stylesheet">
    <link href="../../../public/css/bootstrap-theme.css" rel="stylesheet">

</head>
<body>
<h1>MODULE</h1>
<div class="container">
    <div class="row" id="module_modal">
        <div class="col-lg-12">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary btn-xs btn-block"
                    data-toggle="modal" data-target="#AddModuleModal">
                ADD
            </button>
        </div>

        <form action="ModuleController.php" method="post" class="form-horizontal" role="form">
            <div class="modal fade" id="AddModuleModal" tabindex="-1"
                 role="dialog" aria-labelledby="AddModuleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="AddModuleModalLabel">MODULE</h4>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="inputName" class="col-lg-2 col-md-2 col-sm-2 col-xs-2 control-label">Name</label>
                                <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
                                    <input type="text" class="form-control" id="inputName" name="name" placeholder="Name">
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">CANCEL</button>
                            <button type="submit" class="btn btn-primary">SAVE</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <br>

    <div class="row" id="module_header">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">ID</div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">NAME</div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">ACTION</div>
    </div>
    <?php
        $objModuleController = new ModuleController();
        $modules = $objModuleController->selectAllModuleModel();

        foreach($modules as $value) {
            echo "<div class='row' id='module_body'>
                      <div class='col-lg-4 col-md-4 col-sm-4 col-xs-12'>" . $value['id'] . "</div>
                      <div class='col-lg-4 col-md-4 col-sm-4 col-xs-12'>" . $value['name'] . "</div>
                      <div class='col-lg-4 col-md-4 col-sm-4 col-xs-12'>
                          <button type='button' class='btn btn-primary btn-xs btn-block' id='" . $value['id'] . "'
                                  data-toggle='modal' data-target='#EditModuleModal'>MODIFY</button>
                      </div>
                 </div>";
        }
    ?>

    <form action="ModuleController.php" method="post" class="form-horizontal" role="form">
        <div class="modal fade" id="EditModuleModal" tabindex="-1"
             role="dialog" aria-labelledby="EditModuleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="EditModuleModalLabel">MODULE</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="inputName" class="col-lg-2 col-md-2 col-sm-2 col-xs-2 control-label">Old Name</label>
                            <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
                                <input type="text" class="form-control" id="inputName" name="oldName" placeholder="Name" disabled>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputName" class="col-lg-2 col-md-2 col-sm-2 col-xs-2 control-label">New Name</label>
                            <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
                                <input type="text" class="form-control" id="inputName" name="newName" placeholder="Name">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">CANCEL</button>
                        <button type="submit" class="btn btn-primary">SAVE</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

</div>

</body>
</html>