<!--<html>-->
<!---->
<!--<head>-->
<!--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
<!---->
<!--    <script type="text/javascript">-->
<!--        var obj = {-->
<!--            "moduleId":"1",-->
<!--            "categoryId":"1",-->
<!--            "sourceId":"1",-->
<!--            "quantity":"10",-->
<!--            "older":"true",-->
<!--            "pubDate":"fri, 31 jul 2015 22:20:05 +0300"};-->
<!---->
<!--        function sendTestJSON() {-->
<!--            $.ajax({-->
<!--                "url": "/index/test",-->
<!--                "dataType": "json",-->
<!--                "type": "POST",-->
<!--                "data": JSON.stringify(obj),-->
<!--                "contentType": "application/json;charset=utf-8",-->
<!--                "success": function(data) {-->
<!--                    console.log(data);-->
<!--                }-->
<!--            });-->
<!--        }-->
<!--    </script>-->
<!--</head>-->
<!---->
<!--<body>-->
<!--    <button type="button" onclick="sendTestJSON();">Test</button>-->
<!--</body>-->
<!---->
<!--</html>-->

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Module</title>

    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->
    <!-- Latest compiled and minified CSS -->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">-->
    <!-- Optional theme -->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">-->
    <!-- Latest compiled and minified JavaScript -->
    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>-->

    <!--jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="../../../public/js/jquery-1.11.3.js"></script>
    <!--Include all compiled plugins (below), or include individual files as needed -->
    <script src="../../../public/js/bootstrap.js"></script>
    <!--Bootstrap -->
    <link href="../../../public/css/bootstrap.css" rel="stylesheet">
    <link href="../../../public/css/bootstrap-theme.css" rel="stylesheet">
    <link href="../../../public/css/stylesheet.css" rel="stylesheet">

</head>
<body>

<h1>ADMINISTRATION</h1>
<div class="container">

    <div class="row">
        <div class="col-lg-12">
            <a href="http://diplom/index/module">
                <button type="button" class="btn btn-primary btn-lg btn-block">MODULE</button>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <a href="http://diplom/index/category">
                <button type="button" class="btn btn-primary btn-lg btn-block">CATEGORY</button>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <a href="http://diplom/index/source">
                <button type="button" class="btn btn-primary btn-lg btn-block">SOURCE</button>
            </a>
        </div>
    </div>

</div>

</body>
</html>