<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Module</title>

    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->
    <!-- Latest compiled and minified CSS -->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">-->
    <!-- Optional theme -->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">-->
    <!-- Latest compiled and minified JavaScript -->
    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>-->

    <!--jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="../../../public/js/jquery-1.11.3.js"></script>
    <!--Include all compiled plugins (below), or include individual files as needed -->
    <script src="../../../public/js/bootstrap.js"></script>
    <!--Bootstrap -->
    <link href="../../../public/css/bootstrap.css" rel="stylesheet">
    <link href="../../../public/css/bootstrap-theme.css" rel="stylesheet">

</head>
<body>
<h1>MODULE</h1>
<div class="container">
    <div class="row" id="module_add">
        <div class="col-lg-12">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary btn-xs btn-block"
                    data-toggle="modal" data-target="#AddModuleModal">
                ADD
            </button>
        </div>
        <div class="modal fade" id="AddModuleModal" tabindex="-1"
             role="dialog" aria-labelledby="AddModuleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="AddModuleModalLabel">Название модали</h4>
                    </div>
                    <div class="modal-body">
                        ...
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                        <button type="button" class="btn btn-primary">Сохранить изменения</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row" id="module_header">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">ID</div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">NAME</div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">ACTION</div>
    </div>
    <div class="row" id="module_body">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">ID</div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">NAME</div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <button type="button" class="btn btn-primary btn-xs btn-block">EDIT</button>
        </div>
    </div>
</div>

</body>
</html>